use meralus_engine::WindowDisplay;
use meralus_engine::glium::Texture2d;
use meralus_engine::glium::texture::{MipmapsOption, RawImage2d};
use owo_colors::OwoColorize;
use std::{collections::HashMap, path::Path};

#[derive(Default)]
pub struct TextureLoader {
    texture_name_map: HashMap<String, usize>,
    textures: Vec<Texture2d>,
}

impl TextureLoader {
    pub fn get_id<T: AsRef<str>>(&self, name: T) -> Option<usize> {
        self.texture_name_map.get(name.as_ref()).copied()
    }

    pub fn get_by_id(&self, id: usize) -> Option<&Texture2d> {
        self.textures.get(id)
    }

    pub fn get_by_name<T: AsRef<str>>(&self, name: T) -> Option<&Texture2d> {
        self.texture_name_map
            .get(name.as_ref())
            .and_then(|&texture_id| self.textures.get(texture_id))
    }

    pub fn load<P: AsRef<Path>>(&mut self, display: &WindowDisplay, path: P) {
        let path = path.as_ref();

        println!(
            "[{}] Loading texture at {}",
            "INFO/TextureLoader".bright_green(),
            path.display().bright_blue().bold()
        );

        if let Some(name) = path.file_stem() {
            let name = name.to_string_lossy();

            match image::ImageReader::open(path).and_then(image::ImageReader::with_guessed_format) {
                Ok(value) => {
                    if let Ok(value) = value.decode() {
                        let image = value.to_rgba8();
                        let dimensions = image.dimensions();

                        let image =
                            RawImage2d::from_raw_rgba_reversed(&image.into_raw(), dimensions);

                        if let Ok(value) = Texture2d::with_mipmaps(
                            display,
                            image,
                            MipmapsOption::AutoGeneratedMipmaps,
                        ) {
                            println!(
                                "[{}] Texture mipmap count: {}",
                                "INFO/TextureLoader".bright_green(),
                                value.get_mipmap_levels().bright_blue().bold()
                            );

                            let texture_id = self.textures.len();

                            self.textures.push(value);
                            self.texture_name_map.insert(name.to_string(), texture_id);
                        }
                    }
                }
                Err(err) => panic!("Failed to load texture: {err}"),
            }
        }
    }
}
