[package]
name = "meralus-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-compression = { workspace = true }
tokio = { workspace = true }
meralus-meshing = { workspace = true }
glam = { workspace = true }

[lints]
workspace = true
