name: CI
env:
  CARGO_TERM_COLOR: always
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo clippy --all-targets -- -D warnings
      - name: rustfmt
        run: cargo fmt --all --check
  dev-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu
      - name: Build
        run: cargo build --release --bin meralus-app --target x86_64-unknown-linux-gnu
      - name: Compress
        run: mkdir tmp && cp -r crates/app/resources tmp && cp target/release/meralus-app tmp
      - uses: actions/upload-artifact@v4
        with:
          name: meralus-linux
          path: tmp/**/*
  dev-build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Install target
        run: rustup target add x86_64-pc-windows-msvc
      - name: Build
        run: cargo build --release --bin meralus-app --target x86_64-pc-windows-msvc
      - name: Compress
        run: mkdir tmp && cp -r crates/app/resources tmp && cp target/release/meralus-app.exe tmp
      - uses: actions/upload-artifact@v4
        with:
          name: meralus-win
          path: tmp/**/*
